### ISSUE TITLE
多谢🙏

### ISSUE THREAD

**Issue by Alanpete** [joevess/IPTV#1]
有好的直播源告诉你

**Comment by Alanpete** [comment]
大佬你好，我喜欢这种分类方式
看看能爬这个网址的源不能http://tonkiang.us/
还有这个https://dimaston.github.io/live.m3u
这个最多https://epg.pw/test_channels.m3u
这个也好，可惜这位大佬8个月没更新了https://cdn.jsdelivr.net/gh/zbefine/iptv/iptv.m3u

**Comment by joevess** [comment]
> https://dimaston.github.io/live.m3u

谢谢支持，[](https://dimaston.github.io/live.m3u) [](https://cdn.jsdelivr.net/gh/zbefine/iptv/iptv.m3u) 已加入整合
[](http://tonkiang.us/) 我考虑下

**Comment by joevess** [comment]
> 大佬你好，我喜欢这种分类方式 看看能爬这个网址的源不能http://tonkiang.us/ 还有这个https://dimaston.github.io/live.m3u 这个最多https://epg.pw/test_channels.m3u 这个也好，可惜这位大佬8个月没更新了https://cdn.jsdelivr.net/gh/zbefine/iptv/iptv.m3u

谢谢支持，
https://dimaston.github.io/live.m3u
https://cdn.jsdelivr.net/gh/zbefine/iptv/iptv.m3u 
已加入整合

http://tonkiang.us/ 我考虑下
