### ISSUE TITLE
文件中有不少链接是由#拼起来的，是否应当检查一下

### ISSUE THREAD

**Issue by llzzll** [joevess/IPTV#11]
![image](https://github.com/joevess/IPTV/assets/4136263/b23d40e5-9097-4558-8b15-5142631ea3d2)

**Comment by joevess** [comment]
> ![image](https://private-user-images.githubusercontent.com/4136263/298839245-b23d40e5-9097-4558-8b15-5142631ea3d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxOTgwMTksIm5iZiI6MTcwNjE5NzcxOSwicGF0aCI6Ii80MTM2MjYzLzI5ODgzOTI0NS1iMjNkNDBlNS05MDk3LTQ1NTgtOGIxNS01MTQyNjMxZWEzZDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjVUMTU0ODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmI4ZmRlMTcxOWJjZDAyNzg1MTVlOTNhMmYyMjliOWU2Mjg2NzE4Y2FkYjQ0ZGExZDEwOThkYmFiYWM1MTM0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vaxxFm6qlYgRy90-Hl9zNqngLNTChzSU03-xgjpWeyM)

已处理
