### ISSUE TITLE
关于m3u格式

### ISSUE THREAD

**Issue by hecarli555** [joevess/IPTV#5]
能不能做成m3u格式的，一般播放器更容易适配m3u格式的，谢谢大佬

**Comment by joevess** [comment]
> 能不能做成m3u格式的，一般播放器更容易适配m3u格式的，谢谢大佬

https://raw.githubusercontent.com/joevess/IPTV/main/m3u/home.m3u
https://raw.githubusercontent.com/joevess/IPTV/main/m3u/iptv.m3u
