### ISSUE TITLE
iptv.m3u8播放几十秒就卡主，重新进入还是播放之前的一段，然后又卡住，循环这样。

### ISSUE THREAD

**Issue by tommyhe1217** [joevess/IPTV#9]
iptv.m3u8播放几十秒就卡主，重新进入还是播放之前的一段，然后又卡住，循环这样。
可否增加备用源用于切换。

**Comment by joevess** [comment]
> iptv.m3u8播放几十秒就卡主，重新进入还是播放之前的一段，然后又卡住，循环这样。 可否增加备用源用于切换。

谢谢反馈，可以提供下异常频道；增加备用源在计划中
